Uname = input("Please enter your name: ")
Age = input("Please enter your age: ")
Hnum = input("Please enter your house number: ")
Sname = input("Please enter your street name: ")
print(f"Hi! My name is {Uname}, I am {Age} years old and I live at {Sname} number {Hnum}.")
